---
- name: Vault authentication and secret retrieval
  hosts: all
  # vars:
  #   test3_eng_approle_creds: "{{ lookup('file', '/etc/semaphore/vault-approle-eng.json') | from_json }}"
  #   test3_fin_approle_creds: "{{ lookup('file', '/etc/semaphore/vault-approle-fin.json') | from_json }}"
  roles:
    - role: test3   # Fetch secrets from eng/blockchain and fin/treasury (uses vault role internally)
