---
- name: Debug OS family
  ansible.builtin.debug:
    msg: "OS Family is {{ os_family }}"

- name: Debug condition check for RedHat
  ansible.builtin.debug:
    msg: "RedHat condition: {{ os_family == 'RedHat' }}"

- name: Debug condition check for Debian
  ansible.builtin.debug:
    msg: "Debian condition: {{ os_family == 'Debian' }}"

- name: Update package cache (RedHat)
  become: true
  ansible.builtin.dnf:
    update_cache: yes
  when: os_family == "RedHat"

- name: Upgrade all packages (RedHat)
  become: true
  ansible.builtin.dnf:
    name: "*"
    state: latest
  when: os_family == "RedHat"

- name: Update package cache (Debian)
  become: true
  ansible.builtin.apt:
    update_cache: yes
  when: os_family == "Debian"

- name: Upgrade all packages (Debian)
  become: true
  ansible.builtin.apt:
    upgrade: yes
  when: os_family == "Debian"
