---
- name: Update packages (RedHat)
  when: ansible_os_family == "RedHat"
  block:
    - name: Update package cache (RedHat)
      become: true
      ansible.builtin.dnf:
        update_cache: true

    - name: Upgrade all packages (RedHat)
      become: true
      ansible.builtin.dnf:
        name: "*"
        state: latest

- name: Update packages (Debian)
  when: ansible_os_family == "Debian"
  block:
    - name: Update package cache (Debian)
      become: true
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        allow_unauthenticated: false
        force_apt_get: true
      ignore_errors: true

    - name: Upgrade all packages (Debian)
      become: true
      ansible.builtin.apt:
        upgrade: true
