---
- name: Update package cache (RedHat)
  become: true
  ansible.builtin.dnf:
    update_cache: true
  when: ansible_os_family == "RedHat"

- name: Upgrade all packages (RedHat)
  become: true
  ansible.builtin.dnf:
    name: "*"
    state: latest
  when: ansible_os_family == "RedHat"

- name: Update package cache (Debian)
  become: true
  ansible.builtin.apt:
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Upgrade all packages (Debian)
  become: true
  ansible.builtin.apt:
    upgrade: true
  when: ansible_os_family == "Debian"
