---
- name: Update all packages (RedHat)
  ansible.builtin.yum:
    name: "*"
    state: latest
  when: ansible_os_family == "RedHat"

- name: Update all packages (Debian)
  ansible.builtin.apt:
    name: "*"
    state: latest
  when: ansible_os_family == "Debian"
