---
- name: Print TEST_VAR
  ansible.builtin.debug:
    msg: "TEST_VAR: {{ TEST_VAR }}"

- name: Print all semaphore-related variables
  ansible.builtin.debug:
    msg:
      - "SEMAPHORE: {{ SEMAPHORE | default('undefined') }}"
      - "semaphore: {{ semaphore | default('undefined') }}"
      - "All variables containing 'semaphore': {{ ansible_play_vars | dict2items | selectattr('key', 'match', '.*[Ss][Ee][Mm][Aa][Pp][Hh][Oo][Rr][Ee].*') | map(attribute='key') | list }}"

- name: Print ansible search paths for group_vars and host_vars
  ansible.builtin.debug:
    msg:
      - "inventory_dir: {{ inventory_dir }}"
      - "playbook_dir: {{ playbook_dir }}"
      - "ansible_search_path: {{ ansible_search_path }}"
      - "Current working directory: {{ ansible_env.PWD | default('not set') }}"

- name: Print test3_semaphore
  ansible.builtin.debug:
    msg: "Logging in via {{ 'approle' if (semaphore | default(false) | bool) else 'OIDC' }}"

- name: Debug semaphore variable
  ansible.builtin.debug:
    msg:
      - "semaphore value: {{ semaphore | default('undefined') }}"
      - "semaphore type: {{ (semaphore | default(false)) | type_debug }}"
      - "semaphore as bool: {{ (semaphore | default(false) | bool) }}"
      - "Environment semaphore: {{ lookup('env', 'semaphore') }}"

- name: Print test3_eng_login_token
  ansible.builtin.debug:
    msg: "test3_eng_login_token: {{ test3_eng_login_token }}"

- name: Print eng/blockchain username
  ansible.builtin.debug:
    msg: "eng/blockchain username: {{ test3_eng_username }}"

- name: Print test3_fin_login_token
  ansible.builtin.debug:
    msg: "test3_fin_login_token: {{ test3_fin_login_token }}"

- name: Print fin/treasury username
  ansible.builtin.debug:
    msg: "fin/treasury username: {{ test3_fin_username }}"
